application:
  name: basic-postgres
  server: local
database:
  driver: postgres
  username: agusari
  password: 12345678
  port: 32769
  address: localhost
  databasename: postgres
  schemas: public
  sslmode: verify-full