version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=agusari
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 32768:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7380:8181
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=agusari
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=postgres
      - ENVIRONMENT=local
    env_file:
      - .env