version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=agusari
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    ports:
      - 32768:5432
  redis:
    image: redis
    ports:
      - 32769:6379
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7380:8181
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=agusari
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=postgres